import { AirportDTO } from "./airportDTO";

export interface CreateFlightDTO{
    departureAerodrome: AirportDTO,
    departureTime: string,
    arrivalAerodrome: AirportDTO,
    arrivalTime: string,
    flightDate: Date,
    aircraftRegistration: string,
    aircraftTypeId: number,
    SinglePilotSeTime: string,
    SinglePilotMeTime: string,
    multiPilotTime: string,
    totalTime: string,
    picName: string,
    landingsDay: number,
    landingsNight: number,
    flightConditionNightTime: string,
    flightConditionIfrTime: string,
    picTime: string,
    copilotTime: string,
    dualTime: string,
    instructorTime: string,
    remarks: string,
}